// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvukipghfezkvawpxbhw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2dWtpcGdoZmV6a3Zhd3B4Ymh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MzE4ODUsImV4cCI6MjA2NDIwNzg4NX0.eqNZrGJqOKlp_d3qFO0RcoRkLZpoxRTVrTnHe7bK9kY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);